name: cbl_counter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: '>=2.10.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  cbl: ^2.1.6
  cbl_flutter: ^2.0.4
  cbl_flutter_ce: ^2.1.4
  collection: ^1.15.0
  provider: ^6.0.5
  path_provider: ^2.0.12
  path: ^1.8.0
  rxdart: ^0.27.7
  google_fonts: ^4.0.3

dev_dependencies:
  cbl_dart: ^2.1.7
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: any
  cbl_generator: ^0.2.0+4

flutter:
  uses-material-design: true
