name: cbl_counter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '^2.5.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cbl: ^1.0.0-beta.4
  cbl_flutter: ^1.0.0-beta.4
  collection: ^1.15.0
  provider: ^6.0.0
  path_provider: ^2.0.2
  path: ^1.8.0
  rxdart: ^0.27.1
  google_fonts: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
